version: '3'

services:
  swagger:
    image: swaggerapi/swagger-ui
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      SWAGGER_JSON: /app/api.yaml
